name: KarmaPlugin
version: '${version}'
main: io.github.karmasmp.MainPlugin
api-version: '1.20'
description: "The Paper Plugin for Karma SMP run by SakuraRadio."
authors:
  - Austin
  - Byrt
  - LordMrK
website: "https://github.com/KarmaSMP/KarmaSMP-Plugin"